### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mh-github** [rdeits/cryptics#17]
cryptics $ pip install -r 'requirements.txt'
Collecting PyYAML>=3.11 (from -r requirements.txt (line 1))
  Using cached PyYAML-3.12.tar.gz
Collecting msgpack-python>=0.4.4 (from -r requirements.txt (line 2))
  Using cached msgpack-python-0.4.8.tar.gz
Collecting nltk<3.0,>2.0.1 (from -r requirements.txt (line 3))
  Using cached nltk-2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpNfbMEB
    Now working in /tmp/tmpNfbMEB/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-ObXXvJ/nltk
    Traceback (most recent call last):
      File "setup.py", line 37, in <module>
        exec(open(init_path).read(), d)
      File "<string>", line 8, in <module>
      File "/tmp/tmpNfbMEB/distribute-0.6.21/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/tmpNfbMEB/distribute-0.6.21/setuptools/extension.py", line 2, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/tmpNfbMEB/distribute-0.6.21/setuptools/dist.py", line 6, in <module>
        from setuptools.command.install import install
      File "/tmp/tmpNfbMEB/distribute-0.6.21/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/tmpNfbMEB/distribute-0.6.21/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/tmpNfbMEB/distribute-0.6.21/pkg_resources.py", line 2729, in <module>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmpNfbMEB/distribute-0.6.21/pkg_resources.py", line 700, in subscribe
        callback(dist)
      File "/tmp/tmpNfbMEB/distribute-0.6.21/pkg_resources.py", line 2729, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmpNfbMEB/distribute-0.6.21/pkg_resources.py", line 2229, in activate
        self.insert_on(path)
      File "/tmp/tmpNfbMEB/distribute-0.6.21/pkg_resources.py", line 2330, in insert_on
        "with distribute. Found one at %s" % str(self.location))
    ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/lib/python2.7/dist-packages
    /tmp/pip-build-ObXXvJ/nltk/distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ObXXvJ/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "/tmp/pip-build-ObXXvJ/nltk/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-build-ObXXvJ/nltk/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/tmp/pip-build-ObXXvJ/nltk/distribute_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    IOError: Could not build the egg.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ObXXvJ/nltk/

**Comment by rdeits** [comment]
I think you're hitting https://github.com/pypa/setuptools/issues/543 . Can you do `pip install --upgrade setuptools` and try again?

**Comment by mh-github** [comment]
Yes that worked. Removed the errors thrown with pip install -r 'requirements.txt'

**Comment by rdeits** [comment]
Great, thanks!
